name: Pull Request Workflow
on:
  pull_request:
    branches:
    - main
jobs:
  go-test:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: |
        CGO_ENABLED=0 go test ./...

  helm-test:
    runs-on: ubuntu-latest
    needs: go-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Run env substitution
        run: envsubst < charts/simple-go-app/ci/ci-values.yaml.tpl > charts/simple-go-app/ci/ci-values.yaml
        env:
          IMAGE_TAG: ${{ github.event.pull_request.number }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.0

      - name: Run chart-testing (lint)
        run: ct lint --charts charts/simple-go-app

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/simple_go_app:${{ github.event.pull_request.number }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Run chart-testing (install)
        run: ct install --charts charts/simple-go-app "--set .image.tag=${{ github.event.pull_request.number }}"
